// backend/seedListings.js
// Run with: node seedListings.js
// Requires MONGO_URI in .env

const mongoose = require("mongoose");
const Listing  = require("./models/Listing");
require("dotenv").config();

mongoose.connect(process.env.MONGO_URI);


const data = [
  // ─────────────────────────────────── INDIA ──────────────────────────────
  {
    title: "Sea View Villa Goa",
    description: "Beautiful beachside villa with stunning sunset views over the Arabian Sea. Private pool and direct beach access.",
    price: 4500,
    location: "Goa, India",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    amenities: ["WiFi", "Pool", "AC", "Beach Access", "Parking"],
    property_type: "Villa",
    availability: true,
    // Women safety fields
    womenFriendly: true,
    verified: true,
    guardianNearby: true,
    safetyScore: 4.8,
    cctv: true,
    reception24x7: true,
    nearestHospital: "1.2 km",
    nearestPolice: "800 m",
    emergencySupportAvailable: true,
    femaleStaffAvailable: true,
    wellLitArea: true,
    safeTransportAccess: true,
  },
  {
    title: "Backpacker Hostel Rishikesh",
    description: "Affordable and vibrant hostel steps from the Ganga river. Perfect for yoga enthusiasts and adventure seekers.",
    price: 800,
    location: "Rishikesh, India",
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80",
    amenities: ["WiFi", "Parking", "Common Room", "Lockers", "Free Breakfast"],
    property_type: "Hostel",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: true,
    safetyScore: 3.9,
    cctv: true,
    reception24x7: true,
    nearestHospital: "1.2 km",
    nearestPolice: "800 m",
    emergencySupportAvailable: true,
    femaleStaffAvailable: true,
    wellLitArea: true,
    safeTransportAccess: false,  // Remote Himalayan area – limited transport
  },
  {
    title: "Luxury Palace Hotel Jaipur",
    description: "Royal heritage experience with Mughal architecture, ornate frescoes, and world-class Rajasthani hospitality.",
    price: 7000,
    location: "Jaipur, India",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1600011689032-8b628b8a8747?w=800&q=80",
    amenities: ["Pool", "Spa", "AC", "Fine Dining", "Concierge", "Valet"],
    property_type: "Hotel",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: true,
    safetyScore: 4.8,
    cctv: true,
    reception24x7: true,
    nearestHospital: "2.0 km",
    nearestPolice: "600 m",
    emergencySupportAvailable: true,
    femaleStaffAvailable: true,
    wellLitArea: true,
    safeTransportAccess: true,
  },
  {
    title: "New Delhi Imperial Hotel",
    description: "A grand colonial edifice blending Mughal grandeur with modern luxury. Iconic rooftop vistas of Lutyens' Delhi.",
    price: 16000,
    location: "New Delhi, India",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80",
    amenities: ["Rooftop Pool", "Spa", "Valet Parking", "Fine Dining", "Concierge", "Butler"],
    property_type: "Hotel",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: true,
    safetyScore: 4.9,
    cctv: true,
    reception24x7: true,
    nearestHospital: "3.2 km",
    nearestPolice: "600 m",
    emergencySupportAvailable: true,
    femaleStaffAvailable: true,
    wellLitArea: true,
    safeTransportAccess: true,
  },

  // ──────────────────────────────── MALDIVES ──────────────────────────────
  {
    title: "Overwater Bungalow Maldives",
    description: "Step directly into the crystal-clear Indian Ocean from your private deck. Bioluminescent nights await.",
    price: 38000,
    location: "North Malé Atoll, Maldives",
    rating: 5.0,
    image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80",
    amenities: ["Overwater Deck", "Glass Floor", "Snorkelling Gear", "All-inclusive", "Butler"],
    property_type: "Resort",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: true,
    safetyScore: 4.7,
    cctv: true,
    reception24x7: true,
    nearestHospital: "3.2 km",
    nearestPolice: "400 m",
    emergencySupportAvailable: true,
    femaleStaffAvailable: true,
    wellLitArea: true,
    safeTransportAccess: true,
  },
  {
    title: "Maldives Beachfront Bungalow",
    description: "White coral sand at your doorstep, whale sharks offshore, and a private sundeck kissed by the ocean breeze.",
    price: 34000,
    location: "South Ari Atoll, Maldives",
    rating: 5.0,
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
    amenities: ["Private Beach", "Whale Shark Snorkel", "Sunset Cruise", "All-inclusive", "Private Pool"],
    property_type: "Resort",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: true,
    safetyScore: 4.8,
    cctv: true,
    reception24x7: true,
    nearestHospital: "1.2 km",
    nearestPolice: "800 m",
    emergencySupportAvailable: true,
    femaleStaffAvailable: true,
    wellLitArea: true,
    safeTransportAccess: true,
  },

  // ───────────────────────────────── BALI ─────────────────────────────────
  {
    title: "Ubud Jungle Private Villa",
    description: "A tranquil jungle sanctuary with heated plunge pool, rice terrace views, and authentic Balinese rituals.",
    price: 23000,
    location: "Ubud, Bali, Indonesia",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
    amenities: ["Private Pool", "Rice Terrace View", "Breakfast", "Yoga Pavilion", "Massage"],
    property_type: "Villa",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: true,
    safetyScore: 4.2,
    cctv: true,
    reception24x7: true,
    nearestHospital: "5.2 km",
    nearestPolice: "900 m",
    emergencySupportAvailable: true,
    femaleStaffAvailable: true,
    wellLitArea: false,  // Remote jungle – limited exterior lighting
    safeTransportAccess: true,
  },

  // ────────────────────────────────── EUROPE ──────────────────────────────
  {
    title: "Cliffside Villa Santorini",
    description: "Perched above the caldera with an infinity pool and breathtaking Aegean sunset views. Pure Greek magic.",
    price: 36000,
    location: "Oia, Greece",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80",
    amenities: ["Infinity Pool", "Private Terrace", "Jacuzzi", "Wine Cellar", "Butler"],
    property_type: "Villa",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: false,
    safetyScore: 4.5,
    cctv: true,
    reception24x7: false,
    nearestHospital: "4.5 km",
    nearestPolice: "2.1 km",
    emergencySupportAvailable: false,
    femaleStaffAvailable: false,
    wellLitArea: true,
    safeTransportAccess: true,
  },
  {
    title: "Alpine Chalet Zermatt",
    description: "Ski-in/ski-out timber chalet with iconic Matterhorn views, log fireplace, and private sauna.",
    price: 29000,
    location: "Zermatt, Switzerland",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80",
    amenities: ["Ski-in/Ski-out", "Fireplace", "Mountain View", "Sauna", "Heated Floors"],
    property_type: "Villa",
    availability: false,
    womenFriendly: false,  // Private chalet – no dedicated safety staff
    verified: false,
    guardianNearby: false,
    safetyScore: 3.6,
    cctv: false,
    reception24x7: false,
    nearestHospital: "6.0 km",
    nearestPolice: "3.5 km",
    emergencySupportAvailable: false,
    femaleStaffAvailable: false,
    wellLitArea: true,
    safeTransportAccess: false,
  },
  {
    title: "Amalfi Coast Boutique Hotel",
    description: "Clinging to the cliff above the Tyrrhenian Sea with uninterrupted coastal drama and Limoncello bar.",
    price: 25000,
    location: "Positano, Italy",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80",
    amenities: ["Sea View", "Infinity Pool", "Limoncello Bar", "Boat Hire", "Spa"],
    property_type: "Hotel",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: false,
    safetyScore: 4.4,
    cctv: true,
    reception24x7: true,
    nearestHospital: "8.0 km",
    nearestPolice: "1.5 km",
    emergencySupportAvailable: true,
    femaleStaffAvailable: true,
    wellLitArea: true,
    safeTransportAccess: true,
  },
  {
    title: "Amsterdam Canal Apartment",
    description: "A charming 17th-century canal house with exposed beams, Dutch tile work, and gondola views.",
    price: 11000,
    location: "Amsterdam, Netherlands",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&q=80",
    amenities: ["Canal View", "Bikes Included", "Full Kitchen", "Museum Pass", "Smart TV"],
    property_type: "Apartment",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: false,
    safetyScore: 4.3,
    cctv: false,
    reception24x7: false,
    nearestHospital: "1.8 km",
    nearestPolice: "900 m",
    emergencySupportAvailable: false,
    femaleStaffAvailable: false,
    wellLitArea: true,
    safeTransportAccess: true,
  },
  {
    title: "Prague Old Town Boutique",
    description: "Baroque interiors fused with contemporary design, 200 metres from the Astronomical Clock.",
    price: 10000,
    location: "Prague, Czech Republic",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1590073242678-70ee3fc28f8e?w=800&q=80",
    amenities: ["City Centre", "Wine Bar", "Sauna", "Bicycle Rental", "Concierge"],
    property_type: "Hotel",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: false,
    safetyScore: 4.2,
    cctv: true,
    reception24x7: true,
    nearestHospital: "2.3 km",
    nearestPolice: "700 m",
    emergencySupportAvailable: true,
    femaleStaffAvailable: true,
    wellLitArea: true,
    safeTransportAccess: true,
  },
  {
    title: "Tuscany Vineyard Farmhouse",
    description: "Stone farmhouse amid rolling Chianti vineyards with private wine cellar, infinity pool, and truffle hunting.",
    price: 26000,
    location: "Chianti, Italy",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=800&q=80",
    amenities: ["Wine Cellar", "Infinity Pool", "Vineyard Tours", "Wood-fired Kitchen", "Olive Grove"],
    property_type: "Villa",
    availability: true,
    womenFriendly: false,  // Remote farmhouse, limited safety infrastructure
    verified: false,
    guardianNearby: false,
    safetyScore: 3.7,
    cctv: false,
    reception24x7: false,
    nearestHospital: "12 km",
    nearestPolice: "8.0 km",
    emergencySupportAvailable: false,
    femaleStaffAvailable: false,
    wellLitArea: false,
    safeTransportAccess: false,
  },
  {
    title: "Lisbon Bairro Alto Studio",
    description: "Sun-drenched studio with Moorish tiles, iron balconies, and fado music drifting up through the night.",
    price: 6200,
    location: "Lisbon, Portugal",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    amenities: ["City View", "Azulejo Tiles", "Fast WiFi", "Washing Machine", "Self Check-in"],
    property_type: "Apartment",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: false,
    safetyScore: 4.1,
    cctv: false,
    reception24x7: false,
    nearestHospital: "2.5 km",
    nearestPolice: "600 m",
    emergencySupportAvailable: false,
    femaleStaffAvailable: false,
    wellLitArea: true,
    safeTransportAccess: true,
  },
  {
    title: "Edinburgh Castle View Inn",
    description: "Georgian townhouse hotel with castle and Arthur's Seat views. Tartan interiors, whisky bar, fireside tales.",
    price: 11800,
    location: "Edinburgh, Scotland",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1506377585622-bedcbb027afc?w=800&q=80",
    amenities: ["Castle View", "Whisky Bar", "Afternoon Tea", "Fireplace Lounge", "Bicycle Hire"],
    property_type: "Hotel",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: false,
    safetyScore: 4.3,
    cctv: true,
    reception24x7: true,
    nearestHospital: "1.4 km",
    nearestPolice: "500 m",
    emergencySupportAvailable: true,
    femaleStaffAvailable: true,
    wellLitArea: true,
    safeTransportAccess: true,
  },

  // ─────────────────────────────── MIDDLE EAST & AFRICA ───────────────────
  {
    title: "Dubai Marina Sky Suite",
    description: "Floor-to-ceiling glass on the 42nd floor with panoramic marina and desert views. Ultramodern luxury.",
    price: 28000,
    location: "Dubai, UAE",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80",
    amenities: ["Panoramic View", "Private Gym", "Infinity Pool", "Valet", "Concierge"],
    property_type: "Apartment",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: true,
    safetyScore: 4.8,
    cctv: true,
    reception24x7: true,
    nearestHospital: "1.2 km",
    nearestPolice: "800 m",
    emergencySupportAvailable: true,
    femaleStaffAvailable: true,
    wellLitArea: true,
    safeTransportAccess: true,
  },
  {
    title: "Desert Rose Glamping Camp",
    description: "Luxurious desert glamping under a canopy of stars. Camel treks at dawn, fire pits at dusk.",
    price: 9000,
    location: "Merzouga, Morocco",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&q=80",
    amenities: ["Camel Trek", "Fire Pit", "Traditional Meals", "Star Gazing", "AC Tent"],
    property_type: "Resort",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: true,
    safetyScore: 3.9,
    cctv: false,
    reception24x7: true,
    nearestHospital: "18 km",
    nearestPolice: "5.0 km",
    emergencySupportAvailable: true,
    femaleStaffAvailable: false,
    wellLitArea: false,  // Desert camp – limited night lighting
    safeTransportAccess: false,
  },
  {
    title: "Medina Riad Fès",
    description: "Beautifully restored riad within ancient medina walls. Mosaic courtyards, orange trees, rooftop hammam.",
    price: 8000,
    location: "Fès, Morocco",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800&q=80",
    amenities: ["Rooftop Terrace", "Hammam", "Traditional Breakfast", "Cultural Tours", "Courtyard Garden"],
    property_type: "Hotel",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: true,
    safetyScore: 4.0,
    cctv: true,
    reception24x7: true,
    nearestHospital: "3.0 km",
    nearestPolice: "1.2 km",
    emergencySupportAvailable: true,
    femaleStaffAvailable: true,
    wellLitArea: false,  // Old medina lanes are dimly lit at night
    safeTransportAccess: true,
  },
  {
    title: "Safari Tented Camp Masai Mara",
    description: "Luxury tents on the Mara River bank. Witness the Great Migration from your veranda at sunrise.",
    price: 31000,
    location: "Masai Mara, Kenya",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800&q=80",
    amenities: ["Game Drives", "Full Board", "Sun Deck", "Butler", "Sundowner Safaris"],
    property_type: "Resort",
    availability: true,
    womenFriendly: false,  // Remote wilderness – limited safety infrastructure
    verified: true,
    guardianNearby: true,
    safetyScore: 3.5,
    cctv: false,
    reception24x7: true,
    nearestHospital: "25 km",
    nearestPolice: "12 km",
    emergencySupportAvailable: true,
    femaleStaffAvailable: false,
    wellLitArea: false,
    safeTransportAccess: false,
  },
  {
    title: "Cape Town Maker's Hostel",
    description: "Creative hostel in the Design Quarter. Meet artists, makers, and fellow travellers in a vibrant shared space.",
    price: 3100,
    location: "Cape Town, South Africa",
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1520277739336-7bf67b4dba1a?w=800&q=80",
    amenities: ["Common Room", "Free Breakfast", "Lockers", "Bike Rental", "Rooftop Terrace", "WiFi"],
    property_type: "Hostel",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: true,
    safetyScore: 4.0,
    cctv: true,
    reception24x7: true,
    nearestHospital: "1.2 km",
    nearestPolice: "800 m",
    emergencySupportAvailable: true,
    femaleStaffAvailable: true,
    wellLitArea: true,
    safeTransportAccess: true,
  },

  // ─────────────────────────────────── ASIA ───────────────────────────────
  {
    title: "Kyoto Machiya Townhouse",
    description: "A centuries-old wooden townhouse with zen garden, tatami rooms, and traditional ryokan hospitality.",
    price: 19000,
    location: "Kyoto, Japan",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80",
    amenities: ["Zen Garden", "Tatami Rooms", "Tea Ceremony", "Ofuro Bath", "Yukata Robes"],
    property_type: "Apartment",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: false,
    safetyScore: 4.8,
    cctv: false,
    reception24x7: false,
    nearestHospital: "2.0 km",
    nearestPolice: "700 m",
    emergencySupportAvailable: false,
    femaleStaffAvailable: false,
    wellLitArea: true,
    safeTransportAccess: true,
  },
  {
    title: "Seoul Bukchon Hanok House",
    description: "Traditional Korean hanok with wooden lattice windows, ondol heated floors, and tiled rooftop views.",
    price: 8700,
    location: "Seoul, South Korea",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800&q=80",
    amenities: ["Ondol Heating", "Korean Breakfast", "Hanbok Rental", "Tea Ceremony", "Cultural Workshops"],
    property_type: "Apartment",
    availability: false,
    womenFriendly: true,
    verified: true,
    guardianNearby: false,
    safetyScore: 4.6,
    cctv: true,
    reception24x7: false,
    nearestHospital: "1.5 km",
    nearestPolice: "400 m",
    emergencySupportAvailable: false,
    femaleStaffAvailable: false,
    wellLitArea: true,
    safeTransportAccess: true,
  },
  {
    title: "Ho Chi Minh Backpacker Hub",
    description: "Budget-friendly hostel in buzzing Phạm Ngũ Lão district with rooftop bar and free pho at breakfast.",
    price: 1200,
    location: "Ho Chi Minh City, Vietnam",
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1562790351-d273a961e0e9?w=800&q=80",
    amenities: ["Rooftop Bar", "Free Breakfast", "Lockers", "Tours Desk", "AC", "Fast WiFi"],
    property_type: "Hostel",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: true,
    safetyScore: 4.0,
    cctv: true,
    reception24x7: true,
    nearestHospital: "1.2 km",
    nearestPolice: "800 m",
    emergencySupportAvailable: true,
    femaleStaffAvailable: true,
    wellLitArea: true,
    safeTransportAccess: true,
  },
  {
    title: "Phuket Beachfront Resort",
    description: "Teak pavilions spill onto a private white-sand beach with emerald sea views and Thai wellness rituals.",
    price: 13500,
    location: "Phuket, Thailand",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
    amenities: ["Private Beach", "Beachfront Pool", "Thai Spa", "Water Sports", "Airport Transfer"],
    property_type: "Resort",
    availability: false,
    womenFriendly: true,
    verified: true,
    guardianNearby: false,
    safetyScore: 4.3,
    cctv: true,
    reception24x7: true,
    nearestHospital: "4.0 km",
    nearestPolice: "2.5 km",
    emergencySupportAvailable: true,
    femaleStaffAvailable: true,
    wellLitArea: true,
    safeTransportAccess: true,
  },

  // ─────────────────────────────────── AMERICAS ───────────────────────────
  {
    title: "Tulum Jungle Cenote Villa",
    description: "Eco-luxe villa with a private cenote plunge pool and open-air jungle bedroom. Nature as your suite.",
    price: 21000,
    location: "Tulum, Mexico",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800&q=80",
    amenities: ["Private Cenote", "Open-air Rooms", "Yoga Platform", "Organic Meals", "Hammock Garden"],
    property_type: "Villa",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: true,
    safetyScore: 4.0,
    cctv: true,
    reception24x7: true,
    nearestHospital: "7.0 km",
    nearestPolice: "3.0 km",
    emergencySupportAvailable: true,
    femaleStaffAvailable: true,
    wellLitArea: false,  // Jungle environment – limited perimeter lighting
    safeTransportAccess: true,
  },
  {
    title: "Brooklyn Loft Williamsburg",
    description: "Industrial-chic apartment with exposed brick, high ceilings, and Manhattan skyline views from the terrace.",
    price: 13000,
    location: "New York, USA",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1524230572899-a752b3835840?w=800&q=80",
    amenities: ["City View", "Full Kitchen", "Rooftop Access", "Fast WiFi", "Smart TV", "Washer/Dryer"],
    property_type: "Apartment",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: false,
    safetyScore: 4.1,
    cctv: true,
    reception24x7: false,
    nearestHospital: "1.0 km",
    nearestPolice: "500 m",
    emergencySupportAvailable: false,
    femaleStaffAvailable: false,
    wellLitArea: true,
    safeTransportAccess: true,
  },
  {
    title: "Banff Rocky Mountain Hotel",
    description: "Grand timber hotel flanked by the Rockies with direct skiing access and turquoise glacial lake views.",
    price: 18000,
    location: "Banff, Canada",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&q=80",
    amenities: ["Mountain View", "Heated Pool", "Ski Storage", "Hot Tub", "Wildlife Excursions"],
    property_type: "Hotel",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: false,
    safetyScore: 4.5,
    cctv: true,
    reception24x7: true,
    nearestHospital: "3.5 km",
    nearestPolice: "1.0 km",
    emergencySupportAvailable: true,
    femaleStaffAvailable: true,
    wellLitArea: true,
    safeTransportAccess: true,
  },
  {
    title: "Patagonia Eco Lodge",
    description: "Solar-powered wilderness lodge at the edge of the world. Glacier treks and pristine Andean silence.",
    price: 20000,
    location: "Torres del Paine, Chile",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
    amenities: ["Guided Treks", "Organic Meals", "Kayaking", "Fireplace Lounge", "Off-grid Power"],
    property_type: "Resort",
    availability: true,
    womenFriendly: false,  // Wilderness lodge – no dedicated safety features
    verified: false,
    guardianNearby: false,
    safetyScore: 3.6,
    cctv: false,
    reception24x7: false,
    nearestHospital: "40 km",
    nearestPolice: "30 km",
    emergencySupportAvailable: false,
    femaleStaffAvailable: false,
    wellLitArea: false,
    safeTransportAccess: false,
  },

  // ──────────────────────────────────── OCEANIA ────────────────────────────
  {
    title: "Queenstown Lakeside Lodge",
    description: "Boutique alpine lodge with jaw-dropping Remarkables mountain views and private lake access.",
    price: 16000,
    location: "Queenstown, New Zealand",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&q=80",
    amenities: ["Lake Access", "Mountain View", "Ski Hire", "Kayak/Paddleboard", "Gourmet Breakfast"],
    property_type: "Hotel",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: false,
    safetyScore: 4.6,
    cctv: true,
    reception24x7: true,
    nearestHospital: "2.5 km",
    nearestPolice: "1.2 km",
    emergencySupportAvailable: true,
    femaleStaffAvailable: true,
    wellLitArea: true,
    safeTransportAccess: true,
  },

  // ─────────────────────────── ICELAND & NORDICS ──────────────────────────
  {
    title: "Reykjavik Aurora Studio",
    description: "Glass-ceiling studio apartment designed for Northern Lights viewing with a hot tub on the deck.",
    price: 14000,
    location: "Reykjavik, Iceland",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1531168556467-80aace0d0144?w=800&q=80",
    amenities: ["Glass Ceiling", "Hot Tub", "Aurora Alerts", "Heated Floors", "Golden Circle Tours"],
    property_type: "Apartment",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: false,
    safetyScore: 4.7,
    cctv: false,
    reception24x7: false,
    nearestHospital: "3.0 km",
    nearestPolice: "1.5 km",
    emergencySupportAvailable: false,
    femaleStaffAvailable: false,
    wellLitArea: true,
    safeTransportAccess: true,
  },

  // ─────────────────────────────── JAPAN ──────────────────────────────────
  {
    title: "Tokyo Shibuya Design Hotel",
    description: "Minimalist rooms above the city's most electric crossing. Pure Tokyo energy meets Japanese precision.",
    price: 12500,
    location: "Tokyo, Japan",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80",
    amenities: ["City View", "Fitness Centre", "Rooftop Bar", "Fast WiFi", "Concierge"],
    property_type: "Hotel",
    availability: true,
    womenFriendly: true,
    verified: true,
    guardianNearby: false,
    safetyScore: 4.9,
    cctv: true,
    reception24x7: true,
    nearestHospital: "1.0 km",
    nearestPolice: "300 m",
    emergencySupportAvailable: true,
    femaleStaffAvailable: true,
    wellLitArea: true,
    safeTransportAccess: true,
  },
];

/**
 * Quick safety check:
 * womenFriendly: true count must be >= 70 % of total listings.
 */
const womenFriendlyCount = data.filter((l) => l.womenFriendly).length;
const pct = ((womenFriendlyCount / data.length) * 100).toFixed(1);
console.log(`ℹ  Women-friendly: ${womenFriendlyCount}/${data.length} (${pct}%)`);

const seed = async () => {
  try {
    await Listing.deleteMany();
    await Listing.insertMany(data);
    console.log(`✅ ${data.length} listings inserted successfully!`);
  } catch (err) {
    console.error("❌ Seeding failed:", err.message);
  } finally {
    mongoose.connection.close();
  }
};

seed();
